# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarityviz', '0004_auto_20161114_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute',
            name='bucket',
            field=models.CharField(max_length=30),
        ),
    ]
